### ISSUE TITLE
Hero h1 margin and padding on mobile widths.

### ISSUE THREAD

**Issue by bmartinez287** [ddev/ddev.com#103]
Before

<img width="1037" alt="Screen Shot 2023-09-24 at 7 27 00 PM" src="https://github.com/ddev/ddev.com/assets/39039024/e90b3704-1bfe-4343-a809-718daea8e70b">

After

<img width="609" alt="Screen Shot 2023-09-24 at 7 23 41 PM" src="https://github.com/ddev/ddev.com/assets/39039024/b9bf980f-fa8b-4263-93bc-111967abbaf0">

There seems to be too much margin and padding on mobile devices.
At around 640px width there does not seem to be a need for the top margin and top padding to be so large.

Should I proceed with a PR and change the top margin and padding until it exceeds 640 which is tailwindcss sm breakpoint

**Comment by mattstein** [comment]
Sorry for the slow response @bmartinez287. I agree and your suggestion seems like an improvement. Go for it!

**Comment by bmartinez287** [comment]
no worries
