### ISSUE TITLE
Add @bmartinez287 as privileged maintainer

### ISSUE THREAD

**Issue by rfay** [ddev/ddev.com#112]
@bmartinez287 - 

@mattstein and I have so much appreciated your care and curation of this project, and we'd love to see it continue. I've just given you increased privileges ("write"), which means you can pull PRs or could even commit directly.

I'd like you to not use those privileges at this point, but continue using basically the same process (Discuss, create a PR, get review, get it merged). I guess the only difference would be that if @mattstein tells you to pull it, you CAN!

THANK YOU!

**Comment by mattstein** [comment]
@bmartinez287 If you want to push changes into branches on the repository, you’ll get automatic PR previews from Cloudflare Pages. If you wouldn’t mind assigning me to review when you want my attention, that’d make it easier to leave feedback or merge.

Like Randy said, thanks for improving things around here!

**Comment by rfay** [comment]
Yeah, now that you have write privs @bmartinez287 you can do your PRs on ddev/ddev.com instead of on your fork. I'm all in favor of forked PRs myself, but for a variety of reasons the Cloudflare Pages stuff doesn't work with forked PRs. So try to not use your fork (I've failed several times) and instead use branch on the main repo. 

Also, if you don't set your PR to "Ready for Review" until it is, it helps. @mattstein can't we make it automatically request from you when it's Ready for Review just like it does on ddev/ddev? Put the 2 of you on the "development" team or something?

**Comment by mattstein** [comment]
> Also, if you don't set your PR to "Ready for Review" until it is, it helps. @mattstein can't we make it automatically request from you when it's Ready for Review just like it does on ddev/ddev? Put the 2 of you on the "development" team or something?

Sure, we could add a codeowners file like we did [over yonder](https://github.com/ddev/ddev/pull/4764).
