### ISSUE TITLE
ddev store - new income for ddev foundation.

### ISSUE THREAD

**Issue by bmartinez287** [ddev/ddev.com#114]
Laravel runs a simple store on https://www.bigcartel.com.
It be interesting if ddev could have one as a way to generate funds and encourage people to spend money on merch.

https://laravel.bigcartel.com/

I would buy a ddev T-shirt and maybe some other cool items as they appear.

It would be important that the store can handle most shipping and handling, storage, and other challenges. That way we could focus on adding products and adding ddev branding on them. Even if they take a good margin of the profit this would be added revenue that would help spread the word and provide something tangible for collectors and those interested in contributing to Ddev financially.

I will add it to Discord later and see if there is another issue related to this but I opened it here since it's part of the marketing of ddev that likely belongs more to the ddev.com than the product itself.

**Comment by rfay** [comment]
I'm open to it. Not that optimistic that it adds that much money, but it's fun community. People often ask about t-shirts, etc.

The big problem is somebody has to manage it. And we're overbooked :)

**Comment by rfay** [comment]
I really do think it's a great idea. Love the Laravel products.

**Comment by bmartinez287** [comment]
That's true management is usually what keeps most projects away from it. We have to do plenty of research to minimize the impact that would have. I had a friend who used to sell t-shirts and kind of figured out the middleman thing where one just provides designs and some other company handles shipping, returns, and storage kind of how commercial kitchens work. 
I will do some research and check what other projects seem to thrive with.

**Comment by rfay** [comment]
Tag1 also has a very favorite company they use for swag.

**Comment by rfay** [comment]
Congratulations and thanks!
