### ISSUE TITLE
Duplicate and invalid feed items

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev.com#140]
Today, my feed contained 3 new items from ddev.com

![image](https://github.com/ddev/ddev.com/assets/7234392/7395f71b-102d-4eff-84e0-d369d9432394)

There are several issues here:
- "Working with Vite in DDEV - an introduction" is repeated twice
- "Introducing New DDEV Maintainer Stas Zhuk" appeared in my feed 16 days ago, and is a duplicate.
- The 2 top feeds (5h) are invalid links (`https://ddev.comblog/`)
  - [Working with Vite in DDEV - an introduction](https://ddev.comblog/working-with-vite-in-ddev)
  - [Introducing New DDEV Maintainer Stas Zhuk](https://ddev.comblog/introducing-maintainer-stas)
  
  Update: I'm using https://feedly.com/ as my reader.

**Comment by rfay** [comment]
Thanks for paying attention! Please take a look at https://ddev.com/blog/rss.xml (assuming that's what you're using) and see what you think. 

You might try `curl -s https://ddev.com/blog/rss.xml | xq` (assuming you have xq installed) to review it. 

A quick look didn't make me think there was anything wrong, but we appreciate your sharp eye.

**Comment by tyler36** [comment]
Feedly is subscribed to `https://ddev.com/blog/rss.xml` (same as you suggested)
Eyeballing the feed, the first item looks strange, the link is incorrect.

```xml
<title>Working with Vite in DDEV - an introduction</title>
<link>https://ddev.comblog/working-with-vite-in-ddev</link>
<guid isPermaLink="true">https://ddev.comblog/working-with-vite-in-ddev</guid>
```

Perhaps feedly saw this as a "new" item and hence the duplicate? 
... scanning down the list, all the `link` seem to be missing the `/` between `.com` and `blog`.

**Comment by rfay** [comment]
Want to see if you can sort it out? Sure looks wrong. Suggestions @mattstein ? (Matt has looked into this before). 

I don't know how the missing slash would break what items you're getting though, and don't know how anything can work with the slash missing.

BTW, I see the same thing you do in feedly:

<img width="1097" alt="image" src="https://github.com/ddev/ddev.com/assets/112444/2e782251-86f4-4f25-8397-a6a91475112a">

**Comment by mattstein** [comment]
Whoops! Pretty sure I inadvertently broke the feed URLs [upgrading to Astro 3](https://github.com/ddev/ddev.com/pull/107), sorry!

It looks like the feed [is still valid though](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fddev.com%2Fblog%2Frss.xml), and the `pubDate` values are as I’d expect.

I would bet the changing `guid`s didn’t help the duplicate situation, if they weren’t entirely responsible to start with.

Is it normal for Feedly to display an empty thumbnail? We should probably be fixing the relative links inside post content, and I’m not sure what Feedly’s looking for to display images.

**Comment by tyler36** [comment]
> Is it normal for Feedly to display an empty thumbnail?

Other feeds have images:
![image](https://github.com/ddev/ddev.com/assets/7234392/524298ae-bd20-42d2-8d21-e7abb40dc8df)

**Comment by tyler36** [comment]
>Want to see if you can sort it out?

Didn't even get a chance to setup before @mattstein 's 80476d0c976ebd7af48c88c4d059c56b2f38e522 appeared!

**Comment by mattstein** [comment]
Thanks @tyler36! I’ll dig into this when I get some time and see if I can spruce things up.

**Comment by mattstein** [comment]
The URLs are fixed now, including relative ones within post content.

I’m not sure if there’s anything we can do to convince Feedly that the invalid posts should go away. 😬

**Comment by rfay** [comment]
Beautiful!
