### ISSUE TITLE
Feed images

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev.com#141]
During tracking #140 , it was raised that ddev.com 's feed images were not appearing in [feedly ](https://feedly.com/)(rss reader).

![image](https://github.com/ddev/ddev.com/assets/7234392/950f4c64-a840-4f3d-9bf1-4dab67e209ba)

The top-level image also appears to be using a default image (same as "Matt Glaman" and "PHP" feeds for reference):

![image](https://github.com/ddev/ddev.com/assets/7234392/95ddd6de-b41d-4633-b1b1-dc68ea9eab88)
![image](https://github.com/ddev/ddev.com/assets/7234392/137b9e25-7b63-4203-9d70-3f93eea4f2b5)

We should investigate if this is a feedly issue or an issue with our feed.

**Comment by mattstein** [comment]
The feed is _valid_, but we probably need to make updates to appease Feedly specifically.

The site’s favicon does not exist at the root (ddev.com/favicon.ico), for example, and I’d bet that’s exactly and only what Feedly is looking for. Similarly with those images, I assume Feedly is looking for a summary image we don’t have in place.

**Comment by mattstein** [comment]
It turns out Feedly does have some [automatic and not-so-automatic things it looks for](https://blog.feedly.com/10-ways-to-optimize-your-feed-for-feedly/). Just merged a PR that should now include images and an icon.

**Comment by tyler36** [comment]
Thank you @mattstein 

Feed icon is now displaying
![image](https://github.com/ddev/ddev.com/assets/7234392/932ea444-4ea9-4025-ae54-394e69ae6e2e)

I'm not seeing images for feed items. Not sure if this is a caching issue, or if they will start appearing with new items.
![image](https://github.com/ddev/ddev.com/assets/7234392/89f1d085-19bc-4ca6-9912-5885193e47b9)


I checked the feed on https://rss.app/ (online RSS reader) and images display there so the URL is right.

![image](https://github.com/ddev/ddev.com/assets/7234392/698694ae-afec-4c85-8dca-021ddfe2bf36)

**Comment by mattstein** [comment]
I wasn’t seeing the icon yet @tyler36, so I guess that’s progress! 🤞

**Comment by tyler36** [comment]
There was a new item in DDEV feed but the image did not show up in Feedly.

![image](https://github.com/ddev/ddev.com/assets/7234392/6faafa84-a0f4-41c9-a920-d989cf7f24f6)

The image source does not appear valid: `https://ddev.comhttps://www.drupal.org/files/project-images/ama-live-updates.gif`

```html
<div class="g4xDLgpkc7OtwABY1Ok_ EntryVisual__visual" style="background-image: url(&quot;https://ddev.comhttps://www.drupal.org/files/project-images/ama-live-updates.gif&quot;);"></div>
```

I thought feedly might be doing something so I checked it in https://rss.app/ and the image appeared broken.

![image](https://github.com/ddev/ddev.com/assets/7234392/c19a9163-01ff-424e-9fbe-d7f61f818cc3)

```html
<div><img referrerpolicy="no-referrer" loading="lazy" onerror="this.src.indexOf('https://') === 0 ? this.src=this.src.replace('https://', 'http://') : this.style.display='none'" src="http://ddev.comhttps//www.drupal.org/files/project-images/ama-live-updates.gif" style="width: 100%; display: none;"><div><img src="https://ddev.comhttps://www.drupal.org/files/project-images/ama-live-updates.gif" alt="Acquia Migrate Accelerate Dashboard"><p>This walkthrough is based on the blog post <a href="https://dev.acquia.com/blog/acquia-migrate-accelerate-now-open-source">Acquia Migrate: Accelerate — now open source!</a> by <a href="https://dev.acquia.com/person/employee/wim-leers">Wim Leers</a>.</p>
```


Checking the raw feed: https://rss.app/feeds/GwRYLvc0Z8ezl2yl.xml

```html
<img src="https://ddev.comhttps://www.drupal.org/files/project-images/ama-live-updates.gif" style="width: 100%;" /><div><img src="https://ddev.comhttps://www.drupal.org/files/project-images/ama-live-updates.gif" alt="Acquia Migrate Accelerate Dashboard">
```

**Comment by mattstein** [comment]
Thanks for catching that, @tyler36!

This is because the `featureImage` in this new post is using [a hotlinked, absolute image](https://github.com/ddev/ddev.com/blob/main/src/content/blog/drupal7-drupal9-migration-ddev-acquia-migrate-accelerate.md?plain=1#L8) and not a local one.

I’d recommend bringing the image into ddev.com for longevity, but I also fixed the feed generator so absolute feature image URLs won’t be a problem there. This should be reflected in the feed momentarily.

**Comment by tyler36** [comment]
Images are appearing with the recently published content ...

![image](https://github.com/ddev/ddev.com/assets/7234392/4765b8ef-b18d-49a3-b147-4597a9ab3fb6)

Thank you.

**Comment by mattstein** [comment]
We did it! Thanks again for pointing this out and checking up on it, @tyler36.
