### ISSUE TITLE
ddev.com style guide?

### ISSUE THREAD

**Issue by RowboTony** [ddev/ddev.com#143]
Hello, is there a style guide for the ddev.com website? For example, [ddev readthedocs.io has a style guide](https://ddev.readthedocs.io/en/latest/developers/writing-style-guide/#use-tips). 

I've forked a ddev.com repo to work on adding a blog post. I was trying to add something like a _tip_ or _warning_ to my blog post markdown such as:

```
!!!tip "This is a tip."
    Use it for helpful asides.
```
![ddev-readthedocs](https://github.com/ddev/ddev.com/assets/914143/e34eb4c1-2dc4-4737-8f2f-c882e8d42b09)

Here's the link if anyone wants to review. I hope to complete my commentary comparing traditional migration vs. AM:A by the end of this week.

https://github.com/RowboTony/ddev.com/blob/main/src/content/blog/acquia-migrate-accelerate-ama-on-ddev.md

Thank you,
--Tony

**Comment by rfay** [comment]
Thanks for working on the article @RowboTony !

The feature you're talking about is a feature of [mkdocs-material](https://squidfunk.github.io/mkdocs-material/), which isn't used by ddev.com (it is used by the docs). 

Features like that aren't really related to a style guide though. A style guide typically tells you how to use language and standardize approaches.

**Comment by RowboTony** [comment]
All good, I mostly had to brush up on markdown syntax. I'm satisfied with the markup, and the blog post has been submitted as a PR. Thanks!
