### ISSUE TITLE
Search URLs are all broken, search is unusable

### ISSUE THREAD

**Issue by rfay** [ddev/ddev.com#146]
If you go to https://ddev.com/search/ for example, and search for "different" you'll get 
<img width="923" alt="image" src="https://github.com/ddev/ddev.com/assets/112444/3c8e8b18-5f90-4571-987d-4fabaaae84a8">

But if you click any of the links, they're all missing the hostname, so the top item links to `https://blog/whats-so-different-about-ddev-local/`, which of course doesn't work.

**Comment by rfay** [comment]
@bmartinez287 do you have time to take an initial look at this?

**Comment by bmartinez287** [comment]
I will take a look.
