### ISSUE TITLE
Update Centarro logo images

### ISSUE THREAD

**Issue by rfay** [ddev/ddev.com#198]
We'd like to update the Centarro images

Guides and Illustrator image attached.

[centarro.zip](https://github.com/ddev/ddev.com/files/15180506/centarro.zip)

And png:

![centarro_full](https://github.com/ddev/ddev.com/assets/112444/dc4861a9-66bf-4d7e-9733-a7ace0b64b99)

**Comment by rszrama** [comment]
Ideally, we'd have 3 formats in SVG: white background, dark background, and just a square of the bull. Going to see if anyone on our team can help in that regard - if not, I can reach out to our designer as well.

**Comment by rszrama** [comment]
Depending on the context, I think these would do the trick; the logo versions for a white background, logo negative for a dark background.
![Logo Icon Negative](https://github.com/ddev/ddev.com/assets/17675/5c52f482-3ceb-4939-bf91-8c12ff71a7f3)
![Logo Icon](https://github.com/ddev/ddev.com/assets/17675/60898724-ed34-4eef-bff5-d6e2aaacbf7c)
![Logo Negative](https://github.com/ddev/ddev.com/assets/17675/d1b49e1e-0430-49e5-829f-3fcc40af30bf)
![Logo](https://github.com/ddev/ddev.com/assets/17675/0b230572-4753-4169-8d92-77b48010745e)

**Comment by rfay** [comment]
@bmartinez287 would you mind getting this added?
