### ISSUE TITLE
Add heading anchor icons for linkable sections

### ISSUE THREAD

**Issue by mandrasch** [ddev/ddev.com#205]
Would be cool for longer posts like https://ddev.com/blog/setting-up-a-go-development-environment/ or https://ddev.com/blog/working-with-vite-in-ddev/ where reader wants to link to a specific section

Astro already assigns ids for h2,h3, etc.

Found solutions like this, first quick search:

- https://www.itaydafna.dev/blog/my-take-on-astro-markdown-anchor-headings/
- https://jan-mueller.at/blog/next-level-heading-anchors/
- https://caseyjamesperno.com/blog/astro-header-anchors/

Happy to help if this is interesting

**Comment by rfay** [comment]
Please do, thanks!

**Comment by mandrasch** [comment]
I researched a bit and does not seem to be _that_ easy. Would need more research time / testing time. I'll have no real resources for this currently, feel free to close this.

**Comment by rfay** [comment]
Thanks for studying it!
