### ISSUE TITLE
Licensing implications for using OrbStack in Get Started guide?

### ISSUE THREAD

**Issue by A-Kun** [ddev/ddev.com#286]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

OrbStack is currently used in the [Get Started](https://ddev.com/get-started/) guide for macOS due to it's easiness to install. That said, OrbStack is a commercial software that requires a licence for non-personal use. I think many developers who use DDEV do it for work, and just following the guide might cause them to accidentally break the T&S. 

### Describe your solution

- Clearly state that OrbStack is commercial software?
- Use a FOSS Docker Provider instead?

**Comment by rfay** [comment]
Moved issue to ddev.com.

You'll note that the full docs explain all of this quite well I think, https://ddev.readthedocs.io/en/stable/users/install/docker-installation/

Here it says:
> We’ll use OrbStack since it’s the most straightforward of [several options](https://ddev.readthedocs.io/en/stable/users/install/docker-installation/#macos).

Anybody who installs OrbStack (or Docker Desktop) will know it's commercial software because they make that clear.

If you want to do a PR here that adds one or two words to that sentence pointing this out to people, it will be OK. But we want people to have the easy path right in front of them.

**Comment by A-Kun** [comment]
I see it well-explained in the full docs. That said, I assume many people following the regular [Get Started](https://ddev.com/get-started/) will not be bothered to read the full docs. I don't have analytics to back that statement, but I almost fell for it myself 😛

Taking another look at the [Get Started](https://ddev.com/get-started/) page, there's not a single mention of commercial use. The page only mentions "accept the license agreement", which does imply the end-user should abide by the software's license agreement, but I doubt many people will actually read it when installing software. The guide also uses brew to install OrbStack which bypasses their website where the pricing is explained. 

Anyways, I started https://github.com/ddev/ddev.com/pull/290 which adds a one-sentence note stating that OrbStack is not free for professional use.

**Comment by rfay** [comment]
Thanks! IIRC when using brew to install OrbStack it definitely makes you pay attention at first launch.
