### ISSUE TITLE
Add key sponsors (GitHub or not) to support page

### ISSUE THREAD

**Issue by rfay** [ddev/ddev.com#44]
We have the key leading sponsors on the GitHub README

<img width="945" alt="image" src="https://user-images.githubusercontent.com/112444/233406525-6fc8abe6-d00f-485e-aa75-281c6490ca6d.png">

but we should probably try to get them onto the [ddev.com support page](https://ddev.com/support-ddev/)

**Comment by fabpot** [comment]
What about making platform.sh stand out a little more as being the main current sponsor?

Something like this:

![image](https://user-images.githubusercontent.com/47313/233408927-9f96e646-df20-474d-816c-9f3f6178d203.png)

**Comment by mattstein** [comment]
Is this about the homepage or the support page? (There _isn’t_ a dedicated sponsors page.)

**Comment by mattstein** [comment]
Got it! Is the goal to make sure those sponsors are included in that “Sponsor Development” list, or to specifically make sure they’re included there _and_ add another layer of visual hierarchy?

I’m totally on board with the first, but I don’t think additional visual complexity (with tiers) helps the reader in the context of the support page where the imagery is strictly there to visualize involvement and support the call to action.

**Comment by rfay** [comment]
@fabpot suggested this because he thinks Platform.sh should have a more prominent place. He's right. We could do that many ways.

**Comment by mattstein** [comment]
I agree that Platform.sh should have a more prominent place on ddev.com, just not as suggested specifically in this context.

I’d love to make sure _all_ sponsors are represented in the “Sponsor Development” section of the [Support DDEV](https://ddev.com/support-ddev/) page, and open a separate issue for more broadly promoting and acknowledging sponsors. I can tackle PRs for each one if we’re all happy with that approach.

**Comment by rfay** [comment]
Sounds good to me!

**Comment by mattstein** [comment]
@rfay First part’s done and [ready for review](https://github.com/ddev/ddev.com-front-end/pull/45), and I created [an issue for broader promotion](https://github.com/ddev/ddev.com-front-end/issues/46).

**Comment by rfay** [comment]
I'd still like to get a little farther on this. 
1. I don't think Platform.sh is still prominent enough, would like to see @fabpot 's suggestion in https://github.com/ddev/ddev.com-front-end/issues/44#issuecomment-1516504421
2. I think we probably have this buried too low on the main ddev.com page. Maybe I'm just old, but I don't know that people actually scroll that far down. I'm still not sure where it can be better.
