### ISSUE TITLE
Improve repository list

### ISSUE THREAD

**Issue by rfay** [ddev/ddev.com#77]
On the front page there's a nice repository list that has ddev/ddev and ddev/ddev-contrib and ddev/awesome-ddev. The first one is what we want, but we should add others. Add-ons?

<img width="1053" alt="image" src="https://github.com/ddev/ddev.com-front-end/assets/112444/7747d039-7964-413e-9bc1-b6ec36b18c83">

**Comment by mattstein** [comment]
I chose those by popularity as general starting points people might find interesting. (I’d look at a new GitHub organization’s repositories to see what’s active and popular just to get a sense of things.)

I’m wondering why you’re suggesting we add others. Adding individual links to add-on repositories seems like it could be strangely specific here and amount to noise, where the add-ons section of the docs is the perfect place to introduce the concept and list the breadth of options.

If the goal is to promote the broad availability of add-ons for their functional value, it might be better to do that with a simpler visual treatment similar to softare (PHP, Node.js, MySQL, etc.) and platforms (Drupal, WordPress, etc.) that are more about recognition than featuring repositories.

**Comment by rfay** [comment]
Maybe we don't need anything, not sure. Maybe repositories aren't the communication technique we need. In this case, the problem is that ddev-contrib is dead and obsolete, and awesome-ddev is uninteresting and poorly maintained. I'm just struggling with the value of that section. 

> If the goal is to promote the broad availability of add-ons for their functional value, it might be better to do that with a simpler visual treatment similar to softare (PHP, Node.js, MySQL, etc.) and platforms (Drupal, WordPress, etc.) that are more about recognition than featuring repositories.

Sadly to say, I'm not much of a fan of those visual treatments either but that belongs in another issue. I'm not sure people recognize the logos and they don't seem to present well.

Part of the problem here may be this modern wall-of-frontpage thing where we assume that people keep reading. I'm not sure they do.

**Comment by tyler36** [comment]
I wonder if the repobeats infograph we have on https://github.com/ddev/ddev might be a better replacement?
Too technical?

**Comment by mattstein** [comment]
> I wonder if the repobeats infograph we have on https://github.com/ddev/ddev might be a better replacement?  
> Too technical?

For me it depends on what the goal is. I meant to provide a jumping-off point to popular repositories so the page ended with somewhere to go. Discussed briefly with Randy, and those three options may not be as strong as I thought—so it could be more appropriate to end on “Get Started” and “Documentation” links that mirror the top of the page.

**Comment by rfay** [comment]
My concern in mentioning this was that ddev-contrib and awesome-ddev aren't very useful repos. ddev-contrib is dead. So I immediately thought "What should we put there instead". But after talking with @mattstein I'm more in favor of a simpler approach and just not listing these here. We still need to call people to ddev/ddev though.

**Comment by mattstein** [comment]
> We still need to call people to ddev/ddev though.

@rfay If that’s the case, what about using this image like @tyler36 suggested?

![ddev/ddev contributor pulse infographic](https://camo.githubusercontent.com/611f049c2b9dab89f7b5c34dffd45075869da2ff18b7f164b59e88abe36dbe8e/68747470733a2f2f7265706f62656174732e6178696f6d2e636f2f6170692f656d6265642f393431623034306131373932316539373436353566633031643737333561613335306135333630332e737667)

**Comment by rfay** [comment]
It has potential. It's a little overwhelming :) I'm fine with it! It does focus on what you and I talked about, that when evaluating an open source project you want to know about the health/activity of the project, not just how many stars it has.

**Comment by tyler36** [comment]
It would be nice if we could customize it to show just recent contributions.

> Can I choose which statistics to show? Can I hide statistics?
Not yet, but we have been considering it. If you would like to run your own queries now, check out [Axiom Play](https://play.axiom.co/) and you can play with live GitHub data in a free sandbox!

**Comment by bmartinez287** [comment]
What if, we replaced ddev/ddev-contrib for https://github.com/ddev/ddev-addon-template and ddev/awesome-ddev
for https://github.com/ddev/ddev.com

So there would be a link for,
ddev/ddev
ddev/ddev-addon-template
ddev/ddev.com

I think that infograph is a great addition, but it serves a slightly different purpose.

**Comment by rfay** [comment]
Works for me.
